#define VIAL_KEYBOARD_UID {0xB4, 0x37, 0x4D, 0x01, 0xED, 0xF2, 0xDB, 0x34}
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
#define VIAL_UNLOCK_COMBO_ROWS { 0, 4}

#define VIAL_COMBO_ENTRIES 8
#define VIAL_TAP_DANCE_ENTRIES 8

#define LAYER_STATE_8BIT
